# Generated by Django 5.0.1 on 2024-01-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeID',
            new_name='EmployeeId',
        ),
    ]
